### PR TITLE
2023 03 16 Rishideep - configured GitHub Actions for RoboTutor_2020

### LINKED ISSUE #129: Feature request:  Identify RoboTutor version by commit timestamp instead of number
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
Version number is hard to maintain and auto-increment.

**Describe the solution you'd like**
Name version by commit timestamp instead of version number.

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

### PR DESCRIPTION
**Pull request by rishideepc**
* Configured GitHub actions for RoboTutor_2020

* Incorporated commit timestamp to build-workflow.yml, APK name now includes: branch_name, version_name, date_timestamp

### CODE REVIEW

**Review by JackMostow — CHANGES_REQUESTED** [review]
1. This path seems specific to your particular configuration of file folders.  Will it work on others?  
def keystorePropertiesFile = rootProject.file("/home/runner/work/RoboTutor_2020/RoboTutor_2020/app/src/sample_config_files/sample_keystore.properties")

2. The edit mostly just changed whitespace.  Appending ?w=1 to the URL filters them out.

**Review by JackMostow — APPROVED** [review]
OK AFAIK.

**Review by JackMostow — CHANGES_REQUESTED** [review]
1. Shouldn't newApkName include a timestamp?  Or is it already part of version?
2. What does new File("./../../../../../build/", newApkName) assume about the file structure on the machine where the script runs?  It seems like an excessively strong assumption liable to break on other machines.

**Comment by rishideepc** [comment]
> 1. This path seems specific to your particular configuration of file folders.  Will it work on others?
>    def keystorePropertiesFile = rootProject.file("/home/runner/work/RoboTutor_2020/RoboTutor_2020/app/src/sample_config_files/sample_keystore.properties")
> 2. The edit mostly just changed whitespace.  Appending ?w=1 to the URL filters them out.


Hello Sir!

The "/home/runner/work/" directory is the default working directory for GitHub Actions workflows during pre-merge checks. The path that I added is an extension of the same. It should work on other machines as well.

**Comment by rishideepc** [comment]
> 1. Shouldn't newApkName include a timestamp?  Or is it already part of version?
> 2. What does new File("./../../../../../build/", newApkName) assume about the file structure on the machine where the script runs?  It seems like an excessively strong assumption liable to break on other machines.

1. The 'newApkName' holds the default name that is given to the APK that 'build.gradle' generates. Timestamp is included in the 'build-workflow.yml' file, where the built APK is renamed as 'RoboTutor2020-branchName-versionName-timestamp.apk' (I have drawn inspiration from RTFaceLogin, where GitHub Actions was setup in a similar fashion).

2. It should work on other machines as well, since the 'build.gradle' file stores the generated APK in the mentioned 'build' folder. Once again, the exact same path has also been used in RTFaceLogin's 'build.gradle' file. I have translated the same architecture here. 

https://github.com/RoboTutorLLC/RTFace_Login/blob/development/app/build.gradle#L65

**Review by JackMostow — APPROVED** [review]
Thanks for explaining!  I'll approve and if possible proceed with the merge.  - Jack

**Pull request merged**
