### PR TITLE
Log config name and config.json

### LINKED ISSUE #33: Log config.json to document what configuration generated a log
Kapil Verma  [ ] Log config name & config.json settings at least in verbose log

### PR DESCRIPTION
**Pull request by kapilv19**
Fixes #33

### CODE REVIEW

**Review by iamsh4shank — DISMISSED** [review]
LGTM 
By the way, should we squash the commits also?

**Review by VishnuSanal — COMMENTED** [review]
Hello, @kapilv19 Awesome work :)

One thing I noticed was that the value of `config_version` appears to be empty (refer to the screenshots attached). Is there anything missing? Other than this, the rest looks good to me.

Log File
LogCat

Thanks! - Vishnu

**Review by JackMostow — APPROVED** [review]
config.json will differ but it doesn't matter because it overrides the quick options defaults.

**Review by JackMostow — CHANGES_REQUESTED** [review]
These config variables got renamed for [RoboTutorLLC/RoboTutor_2020] fix screen recording (#37): 
"recording": true, --> "record_screen_video"
"recording_with_audio_enabled": false --> "include_audio_output_in_screen_video"
-- please make sure they're updated in the configuration logging too since they weren't here in this commit.

**Review by sansyrox — APPROVED** [review]
This looks good! 🚀 

Let me merge the other PR before this as this one is stacked on the previous one.

**Review by kapilv19 — COMMENTED** [review]
The variables have been renamed as directed.

**Review by JackMostow — APPROVED** [review]
Shouldn't setDefaults include "show_debug_launcher"?

**Pull request merged**
