### PR TITLE
Unpackaged asset

### PR DESCRIPTION
**Pull request by chirag03k**
Intended to solve issue #29.

Stories should be placed in the downloads folder as follows

Downloads
|___ StoryName
           |___StoryName_LevelName

Debug.json should include the following in the "tutor_data":
```
"tutor_data": "[unpackaged_asset]StoryName_LevelName"
```

### CODE REVIEW

**Review by VishnuSanal — COMMENTED** [review]
Hey, @chirag03k Awesome work :) ( doing this review as advised by @JackMostow )

Just a couple of things I noticed - please see the comments

Other code looks good to me - didn't test the functionality, BTW

Thanks! - Vishnu

**Review by JackMostow — COMMENTED** [review]
replace("sdcard/Download/RoboTutor/assets/story_questions/audio/en//", "") has 2 problems:
1. It applies only to English stories.
2. It assumes a particular location.  The assumption will be violated if this location is changed.

**Review by JackMostow — CHANGES_REQUESTED** [review]
debugVars.containsKey(key)) could use a comment to explain what debugVars and key are.  An example would help.

mPathResolved.replace("sdcard/Download/RoboTutor/assets/story_questions/audio/en//", ""); is also English-specific.

**Review by JackMostow — CHANGES_REQUESTED** [review]
- Should replace("sdcard/Download/RoboTutor/assets/story_questions/audio...","") be broadened to include other assets besides story_questions or audio?
- Defining DATASOURCEPATH etc. in TCONST makes them easy to update.  Good! In contrast, hardwired pathnames in code are risky, especially repeated ones.  Is there a more general way to say "top-level installation folder" than /sdcard/Download, say TCONST.DOWNLOAD_PATH?
- I assume you downgraded log.wtf to log.d because debug.json missing is normal.

**Review by JackMostow — APPROVED** [review]

**Pull request merged**
